# Propiedades de materiales conductores para cálculos eléctricos
# ✅ CORRECCIÓN CRÍTICA: Resistividades corregidas a valores reales según estándares internacionales
# Todas las resistividades están en Ω·mm²/m a 20°C

materials:
  copper:
    name: "Cobre electrolítico"
    symbol: "Cu"
    # ✅ CORREGIDO: Valor anterior (17.2) era 1000x mayor - ahora usar valor estándar real
    # Fuente: IEC 60228, IEEE Std 835, calculadoras de resistencia online
    resistivity_20C: 0.01724          # Ω·mm²/m a 20°C (valor estándar internacional)
    temp_coefficient: 0.00393         # 1/°C (coeficiente de temperatura)
    density: 8960                     # kg/m³
    thermal_conductivity: 401         # W/(m·K)
    melting_point: 1085               # °C
    description: "Cobre electrolítico de alta pureza (99.9%)"
    typical_applications:
      - "Cables de potencia"
      - "Conductores de strings DC"
      - "Cables de conexión AC"
      - "Barras colectoras"
    temperature_range:
      min: -40
      max: 200
    standards:
      - "IEC 60228"
      - "ASTM B3"
      - "EN 60228"
    # ✅ NUEVA INFORMACIÓN: Verificación con fórmulas conocidas
    verification:
      formula_19: "R(Ω/km) ≈ 19/A(mm²) para cobre - da ~1.9Ω/km para 10mm²"
      example_10mm2_30m: "10mm² × 30m = 0.0517Ω según calculadoras estándar"

  aluminum:
    name: "Aluminio aleación 1350"
    symbol: "Al"
    # ✅ CORREGIDO: Valor anterior (28.2) era 1000x mayor - ahora usar valor estándar real
    # Típicamente 1.65x la resistividad del cobre
    resistivity_20C: 0.02825          # Ω·mm²/m a 20°C (≈ 1.64 × cobre)
    temp_coefficient: 0.00403
    density: 2705
    thermal_conductivity: 237
    melting_point: 660
    description: "Aleación de aluminio 1350 para conductores eléctricos"
    typical_applications:
      - "Cables de media tensión"
      - "Líneas de transmisión"
      - "Conductores aéreos"
      - "Cables subterráneos MV"
    temperature_range:
      min: -40
      max: 150
    standards:
      - "IEC 60228"
      - "ASTM B230"
      - "EN 60228"

  silver:
    name: "Plata pura"
    symbol: "Ag"
    # ✅ CORREGIDO: Plata tiene menor resistividad que el cobre (~92% del cobre)
    resistivity_20C: 0.01587          # Ω·mm²/m a 20°C (mejor conductor que cobre)
    temp_coefficient: 0.0038
    density: 10490
    thermal_conductivity: 429
    melting_point: 962
    description: "Plata de alta pureza (aplicaciones especiales)"
    typical_applications:
      - "Contactos eléctricos"
      - "Aplicaciones de alta frecuencia"
      - "Conductores especiales"
    temperature_range:
      min: -40
      max: 180
    note: "Material costoso, uso limitado a aplicaciones especiales"

  copper_alloy:
    name: "Aleación de cobre"
    symbol: "CuSn"
    # ✅ CORREGIDO: Aleaciones de cobre tienen resistividad ligeramente mayor (~107% del cobre puro)
    resistivity_20C: 0.01845          # Ω·mm²/m a 20°C (ligeramente mayor que cobre puro)
    temp_coefficient: 0.00385
    density: 8800
    thermal_conductivity: 380
    melting_point: 1050
    description: "Aleación de cobre con pequeñas cantidades de otros metales"
    typical_applications:
      - "Cables marinos"
      - "Aplicaciones corrosivas"
      - "Conductores especializados"
    temperature_range:
      min: -40
      max: 180

# Factores de corrección adicionales
correction_factors:
  purity_factors:
    copper:
      "99.9%": 1.00
      "99.5%": 1.02
      "99.0%": 1.05
    aluminum:
      "99.5%": 1.00
      "99.0%": 1.03

  environmental_factors:
    humidity_high: 1.01
    salt_environment: 1.02
    industrial: 1.015

# Rangos de temperatura operativa recomendados por tipo de aplicación
application_temp_ranges:
  dc_strings:
    copper:
      normal: [-20, 90]
      extreme: [-40, 120]
    aluminum:
      normal: [-20, 75]
      extreme: [-40, 100]

  ac_circuits:
    copper:
      normal: [-10, 70]
      extreme: [-30, 90]
    aluminum:
      normal: [-10, 60]
      extreme: [-30, 80]

  mv_circuits:
    copper:
      normal: [0, 80]
      extreme: [-20, 100]
    aluminum:
      normal: [0, 70]
      extreme: [-20, 90]

# ✅ CORREGIDO: Información de validación actualizada con valores reales
validation:
  resistivity_ranges:
    # Rangos corregidos según estándares internacionales
    copper: [0.015, 0.020]           # Ω·mm²/m (valores reales)
    aluminum: [0.025, 0.035]         # Ω·mm²/m (valores reales)

  temp_coefficient_ranges:
    copper: [0.0035, 0.0045]
    aluminum: [0.0036, 0.0045]

  # ✅ NUEVA SECCIÓN: Ejemplos de verificación con calculadoras estándar
  verification_examples:
    copper_examples:
      - section: "10mm²"
        length: "30m"
        expected_resistance: "0.0517Ω"
        temp: "20°C"
      - section: "2.5mm²"
        length: "100m"
        expected_resistance: "0.690Ω"
        temp: "20°C"
    
    aluminum_examples:
      - section: "10mm²"
        length: "30m"
        expected_resistance: "0.0848Ω"
        temp: "20°C"

# Metadatos
metadata:
  version: "2.0"                     # ✅ Incrementado por corrección crítica
  last_updated: "2025-07-01"         # ✅ Actualizado
  description: "Propiedades de materiales conductores para cálculos de secciones de cable - VALORES CORREGIDOS"
  units:
    resistivity: "Ω·mm²/m"
    temperature: "°C"
    density: "kg/m³"
    thermal_conductivity: "W/(m·K)"

  references:
    - "IEC 60228 - Conductors of insulated cables"
    - "IEEE Std 835 - Power Cable Ampacity Tables"
    - "CRC Handbook of Chemistry and Physics"
    - "ASM Metals Handbook"
    # ✅ NUEVAS REFERENCIAS: Fuentes de verificación para valores corregidos
    - "Online wire resistance calculators (ohmslaw.eu, omnicalculator.com)"
    - "DesignSpark formula: R(Ω/km) = 19/A(mm²) for copper"
    - "AS/NZS 3008 cable resistance tables"

  notes:
    - "✅ CRÍTICO: Resistividades corregidas - valores anteriores eran 1000x mayores"
    - "Resistividades medidas a 20°C según estándares internacionales"
    - "Coeficientes de temperatura son valores típicos para rangos normales"
    - "Valores pueden variar según pureza y proceso de fabricación"
    - "Para aplicaciones críticas verificar con especificaciones del fabricante"
    - "✅ VERIFICADO: Valores validados contra múltiples calculadoras online estándar"

  # ✅ NUEVA SECCIÓN: Explicación del error anterior y corrección
  correction_notes:
    previous_error: "Los valores anteriores (Cu: 17.2, Al: 28.2) estaban en mΩ·mm²/m pero se interpretaban como Ω·mm²/m"
    correction_applied: "Divididos por 1000 para obtener valores correctos en Ω·mm²/m"
    impact: "Con valores corregidos, secciones calculadas serán realistas (4-35mm² típico vs >1000mm² anterior)"
    validation: "Verificado contra calculadoras estándar y fórmulas conocidas de la industria"