# Configuraciones de normativas eléctricas CONSOLIDADAS
# Incluye: normativas + secciones comerciales + factores de corrección

normativas:
  
  # Normativa IEC (International Electrotechnical Commission)
  IEC:
    name: "IEC 60364 - Instalaciones Eléctricas de Baja Tensión"
    description: "Estándar internacional para instalaciones eléctricas en edificaciones"
    country: "Internacional"
    
    # Factores normativos (NO parámetros de panel)
    correction_factors:
      isc_safety_factor: 1.25    # Factor de seguridad normativo IEC (25%)
      parallel_strings: 1        # Por defecto 1 string por cálculo
    
    # Configuración del cable
    cable:
      type: "H07RN-F"      # Tipo de cable según IEC
      material: "copper"    # Material: copper | aluminum
      insulation: "XLPE"    # Aislamiento: PVC | XLPE | EPR
      max_temp: 90         # Temperatura máxima del conductor (°C)
    
    # Método de instalación
    installation:
      method: "buried"      # buried | tray_perforated | tray_non_perforated | conduit
      depth_cm: 70         # Profundidad de enterrado (cm) - IEC recomienda 70cm mínimo
      layout: "single_layer" # single_layer | multilayer
      separation: true     # Separación térmica entre cables
      soil_thermal_resistivity: 1.0  # Resistividad térmica del suelo (K·m/W)
    
    # Factores de corrección por temperatura ambiente
    temperature_correction:
      ambient_design: 35  # Temperatura ambiente de diseño (°C)
      reference_temp: 20   # Temperatura de referencia (°C)
      values:
        20: 1.15
        25: 1.08
        30: 1.04
        35: 1.00
        40: 0.96
        45: 0.91
        50: 0.87
        55: 0.82
        60: 0.76
      
    # Factores de agrupamiento según método de instalación
    grouping_factors:
      buried:
        single_layer:
          values:
            1: 1.00
            2: 0.95
            3: 0.89
            4: 0.86
            5: 0.83
            6: 0.80
            7: 0.78
            8: 0.76
            9: 0.75
            "10+": 0.73
        multilayer:
          values:
            1: 0.95
            2: 0.90
            3: 0.85
            "4+": 0.80
      
      tray_perforated:
        values:
          1: 1.00
          2: 0.95
          3: 0.87
          4: 0.84
          5: 0.80
          6: 0.78
          "7+": 0.75
      
      tray_non_perforated:
        values:
          1: 1.00
          2: 0.92
          3: 0.84
          4: 0.80
          5: 0.76
          "6+": 0.72
      
      conduit:
        values:
          1: 1.00
          2: 0.90
          3: 0.80
          4: 0.75
          "5+": 0.70
    
    # Secciones comerciales según IEC (CONSOLIDADO AQUÍ)
    standard_sections:
      dc_strings:
        mm2: [4, 6, 10, 16, 25, 35, 50, 70, 95, 120]
        description: "Secciones para strings fotovoltaicos DC según IEC"
        typical_current_range: "5-15 A"
        max_recommended_length: "500 m"
      
      level_1_dc:
        mm2: [16, 25, 35, 50, 70, 95, 120, 150, 185, 240]
        description: "Secciones para combinadores DC según IEC"
        typical_current_range: "50-200 A"
        max_recommended_length: "1000 m"

      cn1_inverter:
        mm2: [16, 25, 35, 50, 70, 95, 120, 150, 185, 240,300,400,500,630]
        description: "Secciones para combinadores DC según IEC"
        typical_current_range: "50-200 A"
        max_recommended_length: "1000 m"
      
      ac_circuits:
        mm2: [25, 35, 50, 70, 95, 120, 150, 185, 240, 300, 400, 500]
        description: "Secciones para circuitos AC según IEC"
        typical_current_range: "100-1000 A"
        max_recommended_length: "2000 m"
      
      mv_circuits:
        mm2: [50, 70, 95, 120, 150, 185, 240, 300, 400, 500, 630, 800]
        description: "Secciones para media tensión según IEC"
        typical_current_range: "200-2000 A"
        max_recommended_length: "5000 m"
    
    # Caída de tensión
    voltage_drop:
      max_percentage: 1.5   # Máxima caída de tensión permitida (%)
      reference_voltage: 1500  # Tensión de referencia (V)
      calculation_method: "simple"  # simple | exact
    
    # Configuraciones adicionales
    safety_factors:
      current_safety: 1.0   # Factor de seguridad adicional para corriente
      voltage_safety: 1.0   # Factor de seguridad adicional para tensión
    
    standards_reference:
      primary: "IEC 60364-5-52"
      secondary: ["IEC 60287", "IEC 60502"]

  # Normativa NEC (National Electrical Code - Estados Unidos)
  NEC:
    name: "NEC 2023 - National Electrical Code"
    description: "Código Eléctrico Nacional de Estados Unidos"
    country: "Estados Unidos"
    
    # Factores normativos (NEC es más conservador)
    correction_factors:
      isc_safety_factor: 1.56    # NEC usa 156% (factor 1.56)
      parallel_strings: 1
    
    # Configuración del cable (tipos NEC)
    cable:
      type: "USE-2"         # Tipo de cable para aplicaciones fotovoltaicas
      material: "copper"
      insulation: "XLPE"
      max_temp: 90
    
    # Instalación más conservadora
    installation:
      method: "conduit"     # NEC favorece instalación en conduit
      depth_cm: 61         # 24 pulgadas = 61 cm
      layout: "single_layer"
      separation: true
      soil_thermal_resistivity: 0.9  # Valor típico para US
    
    # Factores de corrección NEC (más estrictos)
    temperature_correction:
      ambient_design: 40  # NEC usa temperaturas más altas de diseño
      reference_temp: 30   # Temperatura de referencia NEC
      values:
        21: 1.08
        26: 1.04
        31: 1.00
        36: 0.96
        41: 0.91
        46: 0.87
        51: 0.82
        56: 0.76
        61: 0.71
      
    grouping_factors:
      conduit:
        values:
          1: 1.00
          2: 0.80      # NEC es más estricto en agrupamiento
          3: 0.70
          4: 0.65
          "5+": 0.60
      
      tray_perforated:
        values:
          1: 1.00
          2: 0.85
          3: 0.79
          4: 0.75
          5: 0.73
          "6+": 0.70
      
      buried:
        single_layer:
          values:
            1: 1.00
            2: 0.90
            3: 0.85
            4: 0.82
            "5+": 0.80
    
    # Secciones comerciales según NEC/UL (diferentes a IEC)
    standard_sections:
      dc_strings:
        mm2: [4, 6, 10, 16, 25, 35, 50]  # NEC más conservador para strings
        description: "Secciones para strings DC según NEC"
        typical_current_range: "5-15 A"
        max_recommended_length: "300 m"
      
      level_1_dc:
        mm2: [16, 25, 35, 50, 70, 95, 120, 150, 185]
        description: "Secciones para combinadores DC según NEC"
        typical_current_range: "50-200 A"
        max_recommended_length: "800 m"
      
      ac_circuits:
        mm2: [25, 35, 50, 70, 95, 120, 150, 185, 240, 300, 400]  # Hasta 400 típico en NEC
        description: "Secciones para circuitos AC según NEC"
        typical_current_range: "100-800 A"
        max_recommended_length: "1500 m"
      
      mv_circuits:
        mm2: [70, 95, 120, 150, 185, 240, 300, 400, 500]
        description: "Secciones para media tensión según NEC"
        typical_current_range: "200-1500 A"
        max_recommended_length: "3000 m"
    
    # Caída de tensión más permisiva en NEC
    voltage_drop:
      max_percentage: 3.0   # NEC permite hasta 3%
      reference_voltage: 1500
      calculation_method: "simple"
    
    safety_factors:
      current_safety: 1.25  # Factor de seguridad adicional NEC
      voltage_safety: 1.0
    
    standards_reference:
      primary: "NFPA 70 - NEC 2023"
      secondary: ["UL 4703", "IEEE 1547"]

  # Normativa personalizada (plantilla editable)
  PERSONALIZADA:
    name: "Configuración Personalizada"
    description: "Parámetros definidos por el usuario"
    country: "Personalizado"
    
    # Valores por defecto conservadores
    correction_factors:
      isc_safety_factor: 1.25
      parallel_strings: 1
    
    cable:
      type: "Personalizado"
      material: "copper"
      insulation: "XLPE"
      max_temp: 90
    
    installation:
      method: "buried"
      depth_cm: 60
      layout: "single_layer"
      separation: true
      soil_thermal_resistivity: 1.2
    
    temperature_correction:
      ambient_design: 35
      reference_temp: 20
      values:
        25: 1.08
        30: 1.04
        35: 1.00
        40: 0.96
        45: 0.91
        50: 0.87
      
    grouping_factors:
      buried:
        single_layer:
          values:
            1: 1.00
            2: 0.95
            3: 0.90
            "4+": 0.85
      conduit:
        values:
          1: 1.00
          2: 0.85
          3: 0.75
          "4+": 0.70
      tray_perforated:
        values:
          1: 1.00
          2: 0.90
          3: 0.85
          "4+": 0.80
    
    # Secciones personalizables
    standard_sections:
      dc_strings:
        mm2: [4, 6, 10, 16, 25, 35, 50, 70, 95]
        description: "Secciones personalizadas para strings DC"
        typical_current_range: "5-15 A"
        max_recommended_length: "500 m"
      
      level_1_dc:
        mm2: [16, 25, 35, 50, 70, 95, 120, 150, 185]
        description: "Secciones personalizadas para nivel 1 DC"
        typical_current_range: "50-200 A"
        max_recommended_length: "1000 m"
      
      ac_circuits:
        mm2: [25, 35, 50, 70, 95, 120, 150, 185, 240, 300, 400]
        description: "Secciones personalizadas para AC"
        typical_current_range: "100-1000 A"
        max_recommended_length: "2000 m"
      
      mv_circuits:
        mm2: [50, 70, 95, 120, 150, 185, 240, 300, 400, 500]
        description: "Secciones personalizadas para MV"
        typical_current_range: "200-2000 A"
        max_recommended_length: "5000 m"
    
    voltage_drop:
      max_percentage: 2.0
      reference_voltage: 1500
      calculation_method: "simple"
    
    safety_factors:
      current_safety: 1.0
      voltage_safety: 1.0
    
    standards_reference:
      primary: "Definido por usuario"
      secondary: []

# Reglas de selección automática (consolidado de standard_sections.yaml)
circuit_selection_rules:
  auto_detection:
    dc_strings:
      max_current_threshold: 30  # A
      voltage_level: "DC_LV"
    
    level_1_dc:
      max_current_threshold: 300  # A
      voltage_level: "DC_MV"
    
    ac_circuits:
      min_current_threshold: 50   # A
      voltage_level: "AC_LV"
    
    mv_circuits:
      min_current_threshold: 300  # A
      voltage_level: "MV"

# Metadatos del archivo
metadata:
  version: "2.0"
  last_updated: "2025-06-30"
  description: "Configuraciones CONSOLIDADAS de normativas eléctricas"
  
  # Información sobre parámetros editables
  editable_parameters:
    basic: ["isc_safety_factor", "parallel_strings"]
    cable: ["material", "max_temp", "type", "insulation"]
    installation: ["method", "depth_cm", "layout", "separation"]
    temperature: ["ambient_design"]
    voltage: ["max_percentage", "reference_voltage"]
    safety: ["current_safety", "voltage_safety"]
    sections: ["standard_sections"]  # Las secciones también son editables
  
  # Valores válidos para selects
  valid_values:
    cable_material: ["copper", "aluminum"]
    cable_insulation: ["PVC", "XLPE", "EPR"]
    installation_method: ["buried", "tray_perforated", "tray_non_perforated", "conduit"]
    layout: ["single_layer", "multilayer"]
    calculation_method: ["simple", "exact"]
  
  # Rangos válidos para validación
  parameter_ranges:
    isc_safety_factor: [1.0, 2.0]
    parallel_strings: [1, 20]
    max_temp: [60, 120]
    depth_cm: [30, 150]
    ambient_design: [15, 70]
    max_percentage: [0.5, 5.0]
    reference_voltage: [400, 2000]